[package]
name = "create-user-op"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-core = "0.7.6"
alloy-dyn-abi = "0.7.6"
alloy-sol-types = "0.7.6"
